title: Osiset
email: tyler@osiset.com
description: Code ramblings.
baseurl: ""
url: "https://osiset.com"
github_username:  osiset
markdown: kramdown
css: inline
sass:
  style: compressed
paginate_path: /page/:num/
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
defaults:
  -
    scope:
      path: "assets/**/*.pdf"
    values:
      sitemap: false
